serverAddr = "111.230.110.95"
serverPort = 7000

[auth]
token = "soybean_secure_token_2025"

[[proxies]]
name = "backend-api"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3000
remotePort = 8080

[[proxies]]
name = "frontend-web"
type = "tcp"
localIP = "127.0.0.1"
localPort = 9527
remotePort = 8081
