/* prettier-ignore */
/* eslint-disable */
// Generated by elegant-router
// Read more: https://github.com/mufeng889/elegant-router
// Vue auto route: https://github.com/soybeanjs/elegant-router
// 请不要手动修改此文件，否则会导致优雅路由无法正常工作
// 如果需要修改，请在优雅路由配置文件中进行修改
// 这是自动生成的文件，请不要手动修改

//这里只能修改 handle 并且路由组作为布局路由组件 是不能有handle的

import type { ElegantConstRoute } from '@soybean-react/vite-plugin-react-router';

export const generatedRoutes: ElegantConstRoute[] = [
  {
    matchedFiles: ['root', '/src/pages/index.tsx', '/src/pages/loading.tsx', 'root'],
    name: 'root',
    path: '/',
    handle: { i18nKey: 'route.root', title: 'root', constant: true },
    children: [
      {
        matchedFiles: ['(base)', null, null, null],
        name: '(base)',
        children: [
          {
            matchedFiles: [null, '/src/pages/(base)/about/index.tsx', null, null],
            name: '(base)_about',
            path: '/about',
            handle: { i18nKey: 'route.(base)_about', title: '(base)_about' }
          },
          {
            matchedFiles: [null, '/src/pages/(base)/class-manage/layout.tsx', null, null],
            name: '(base)_class-manage',
            path: '/class-manage',
            handle: {
              i18nKey: 'route.(base)_class-manage',
              title: '(base)_class-manage',
              hideInMenu: false,
              icon: 'mdi:account-group',
              order: 3
            },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/class-manage/category/index.tsx', null, null],
                name: '(base)_class-manage_category',
                path: '/class-manage/category',
                handle: { i18nKey: 'route.(base)_class-manage_category', title: '(base)_class-manage_category' }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/class-manage/detail/index.tsx', null, null],
                name: '(base)_class-manage_detail',
                path: '/class-manage/detail',
                handle: {
                  i18nKey: 'route.(base)_class-manage_detail',
                  title: '(base)_class-manage_detail',
                  hideInMenu: true
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/class-manage/list/index.tsx', null, null],
                name: '(base)_class-manage_list',
                path: '/class-manage/list',
                handle: {
                  i18nKey: 'route.(base)_class-manage_list',
                  title: '(base)_class-manage_list',
                  hideInMenu: false,
                  icon: 'mdi:format-list-bulleted',
                  order: 1
                }
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(base)/course-manage/index.tsx', null, null],
            name: '(base)_course-manage',
            path: '/course-manage',
            handle: {
              i18nKey: 'route.(base)_course-manage',
              title: '(base)_course-manage',
              icon: 'mdi:book-open-variant',
              order: 2,
              hideInMenu: true
            },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/course-manage/attachments/index.tsx', null, null],
                name: '(base)_course-manage_attachments',
                path: '/course-manage/attachments',
                handle: {
                  i18nKey: 'route.(base)_course-manage_attachments',
                  title: '(base)_course-manage_attachments',
                  hideInMenu: true
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/course-manage/category/index.tsx', null, null],
                name: '(base)_course-manage_category',
                path: '/course-manage/category',
                handle: {
                  i18nKey: 'route.(base)_course-manage_category',
                  title: '(base)_course-manage_category',
                  icon: 'mdi:folder-multiple-outline',
                  order: 2,
                  hideInMenu: true
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/course-manage/class/layout.tsx', null, null],
                name: '(base)_course-manage_class',
                path: '/course-manage/class',
                handle: {
                  i18nKey: 'route.(base)_course-manage_class',
                  title: '(base)_course-manage_class',
                  hideInMenu: true
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/course-manage/class/detail/index.tsx', null, null],
                    name: '(base)_course-manage_class_detail',
                    path: '/course-manage/class/detail',
                    handle: {
                      i18nKey: 'route.(base)_course-manage_class_detail',
                      title: '(base)_course-manage_class_detail',
                      hideInMenu: true
                    },
                    index: false
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/course-manage/detail/index.tsx', null, null],
                name: '(base)_course-manage_detail',
                path: '/course-manage/detail',
                handle: { i18nKey: 'route.(base)_course-manage_detail', title: '(base)_course-manage_detail' }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/course-manage/list/index.tsx', null, null],
                name: '(base)_course-manage_list',
                path: '/course-manage/list',
                handle: {
                  i18nKey: 'route.(base)_course-manage_list',
                  title: '(base)_course-manage_list',
                  icon: 'mdi:format-list-bulleted',
                  order: 1,
                  hideInMenu: true
                }
              }
            ]
          },
          {
            matchedFiles: ['(base)_customer-manage', null, null, null],
            name: '(base)_customer-manage',
            path: '/customer-manage',
            handle: {
              i18nKey: 'route.(base)_customer-manage',
              title: '客户管理',
              icon: 'mdi:account-supervisor',
              order: 4
            },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/customer-manage/assign/index.tsx', null, null],
                name: '(base)_customer-manage_assign',
                path: '/customer-manage/assign',
                handle: {
                  i18nKey: 'route.(base)_customer-manage_assign',
                  title: '客户分配',
                  icon: 'ic:round-assignment-ind',
                  order: 0
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/customer-manage/follow/index.tsx', null, null],
                name: '(base)_customer-manage_follow',
                path: '/customer-manage/follow',
                handle: {
                  i18nKey: 'route.(base)_customer-manage_follow',
                  title: '客户跟进',
                  icon: 'ic:round-transfer-within-a-station',
                  order: 1
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/customer-manage/import/index.tsx', null, null],
                name: '(base)_customer-manage_import',
                path: '/customer-manage/import',
                handle: {
                  i18nKey: 'route.(base)_customer-manage_import',
                  title: '客户导入',
                  icon: 'ic:round-file-upload',
                  order: 2
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/customer-manage/info/index.tsx', null, null],
                name: '(base)_customer-manage_info',
                path: '/customer-manage/info',
                handle: {
                  i18nKey: 'route.(base)_customer-manage_info',
                  title: '客户资料',
                  icon: 'ic:round-contacts',
                  order: 3
                }
              }
            ]
          },
          {
            matchedFiles: [null, null, null, null],
            name: '(base)_employee-manage',
            path: '/employee-manage',
            handle: {
              i18nKey: 'route.(base)_employee-manage',
              icon: 'mdi:account-cog-outline',
              order: 11,
              title: '(base)_employee-manage'
            },
            children: [
              {
                matchedFiles: [null, null, null, null],
                name: '(base)_employee-manage_address',
                path: '/employee-manage/address',
                handle: {
                  i18nKey: 'route.(base)_employee-manage_address',
                  icon: 'mdi:map-marker-outline',
                  order: 3,
                  title: '(base)_employee-manage_address'
                }
              },
              {
                matchedFiles: [null, null, null, null],
                name: '(base)_employee-manage_contact',
                path: '/employee-manage/contact',
                handle: {
                  i18nKey: 'route.(base)_employee-manage_contact',
                  icon: 'mdi:phone-outline',
                  order: 4,
                  title: '(base)_employee-manage_contact'
                }
              },
              {
                matchedFiles: [null, null, null, null],
                name: '(base)_employee-manage_identity',
                path: '/employee-manage/identity',
                handle: {
                  i18nKey: 'route.(base)_employee-manage_identity',
                  icon: 'mdi:card-account-details-outline',
                  order: 2,
                  title: '(base)_employee-manage_identity'
                }
              },
              {
                matchedFiles: [null, null, null, null],
                name: '(base)_employee-manage_list',
                path: '/employee-manage/list',
                handle: {
                  i18nKey: 'route.(base)_employee-manage_list',
                  icon: 'mdi:account-multiple-outline',
                  order: 1,
                  title: '(base)_employee-manage_list'
                }
              }
            ]
          },
          {
            matchedFiles: [null, null, null, null],
            name: '(base)_expense-process',
            path: '/expense-process',
            handle: {
              i18nKey: 'route.(base)_expense-process',
              title: '报销流程',
              icon: 'mdi:file-document-edit-outline',
              order: 6
            },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/expense-process/apply/index.tsx', null, null],
                name: '(base)_expense-process_apply',
                path: '/expense-process/apply',
                handle: {
                  i18nKey: 'route.(base)_expense-process_apply',
                  title: '报销申请',
                  icon: 'mdi:file-document-plus-outline',
                  order: 1
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/expense-process/approve/index.tsx', null, null],
                name: '(base)_expense-process_approve',
                path: '/expense-process/approve',
                handle: {
                  i18nKey: 'route.(base)_expense-process_approve',
                  title: '报销审核',
                  icon: 'mdi:file-check-outline',
                  order: 2
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/expense-process/history/index.tsx', null, null],
                name: '(base)_expense-process_history',
                path: '/expense-process/history',
                handle: { i18nKey: 'route.(base)_expense-process_history', title: '(base)_expense-process_history' }
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(base)/finance-dashboard/index.tsx', null, null],
            name: '(base)_finance-dashboard',
            path: '/finance-dashboard',
            handle: { i18nKey: 'route.(base)_finance-dashboard', title: '(base)_finance-dashboard' }
          },
          {
            matchedFiles: [null, null, null, null],
            name: '(base)_function',
            path: '/function',
            handle: {
              i18nKey: 'route.(base)_function',
              icon: 'icon-park-outline:all-application',
              order: 6,
              title: 'function'
            },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/function/event-bus/index.tsx', null, null],
                name: '(base)_function_event-bus',
                path: '/function/event-bus',
                handle: {
                  i18nKey: 'route.(base)_function_event-bus',
                  icon: 'ant-design:send-outlined',
                  title: 'function_event-bus'
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/function/hide-child/index.tsx', null, null],
                name: '(base)_function_hide-child',
                path: '/function/hide-child',
                handle: {
                  i18nKey: 'route.(base)_function_hide-child',
                  icon: 'material-symbols:filter-list-off',
                  order: 2,
                  title: 'function_hide-child'
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/function/hide-child/one/index.tsx', null, null],
                    name: '(base)_function_hide-child_one',
                    path: '/function/hide-child/one',
                    handle: {
                      activeMenu: '/function/hide-child',
                      hideInMenu: true,
                      i18nKey: 'route.(base)_function_hide-child_one',
                      title: 'function_hide-child_one'
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/function/hide-child/three/index.tsx', null, null],
                    name: '(base)_function_hide-child_three',
                    path: '/function/hide-child/three',
                    handle: {
                      activeMenu: '/function/hide-child',
                      hideInMenu: true,
                      i18nKey: 'route.(base)_function_hide-child_three',
                      title: 'function_hide-child_three'
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/function/hide-child/two/index.tsx', null, null],
                    name: '(base)_function_hide-child_two',
                    path: '/function/hide-child/two',
                    handle: {
                      activeMenu: '/function/hide-child',
                      hideInMenu: true,
                      i18nKey: 'route.(base)_function_hide-child_two',
                      title: 'function_hide-child_two'
                    }
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/function/multi-tab/index.tsx', null, null],
                name: '(base)_function_multi-tab',
                path: '/function/multi-tab',
                handle: {
                  activeMenu: '/function/tab',
                  hideInMenu: true,
                  i18nKey: 'route.(base)_function_multi-tab',
                  icon: 'ic:round-tab',
                  multiTab: true,
                  title: 'function_multi-tab'
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/function/request/index.tsx', null, null],
                name: '(base)_function_request',
                path: '/function/request',
                handle: {
                  i18nKey: 'route.(base)_function_request',
                  icon: 'carbon:network-overlay',
                  order: 3,
                  title: 'function_request'
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/function/super-page/index.tsx', null, null],
                name: '(base)_function_super-page',
                path: '/function/super-page',
                handle: {
                  i18nKey: 'route.(base)_function_super-page',
                  icon: 'ic:round-supervisor-account',
                  order: 5,
                  roles: ['super_admin'],
                  title: 'function_super-page'
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/function/tab/index.tsx', null, null],
                name: '(base)_function_tab',
                path: '/function/tab',
                handle: {
                  i18nKey: 'route.(base)_function_tab',
                  icon: 'ic:round-tab',
                  keepAlive: true,
                  order: 1,
                  title: 'function_tab'
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/function/toggle-auth/index.tsx', null, null],
                name: '(base)_function_toggle-auth',
                path: '/function/toggle-auth',
                handle: {
                  i18nKey: 'route.(base)_function_toggle-auth',
                  icon: 'ic:round-construction',
                  order: 4,
                  title: 'function_toggle-auth'
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/function/use-request/index.tsx', null, null],
                name: '(base)_function_use-request',
                path: '/function/use-request',
                handle: { i18nKey: 'route.(base)_function_use-request', title: '(base)_function_use-request' }
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(base)/home/index.tsx', null, null],
            name: '(base)_home',
            path: '/home',
            handle: { i18nKey: 'route.(base)_home', icon: 'mdi:monitor-dashboard', order: 0, title: 'home' }
          },
          {
            matchedFiles: [null, '/src/pages/(base)/manage/index.tsx', null, null],
            name: '(base)_manage',
            path: '/manage',
            handle: {
              i18nKey: 'route.(base)_manage',
              icon: 'carbon:cloud-service-management',
              order: 8,
              roles: ['super_admin'],
              title: 'manage'
            },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/manage/customer-assign/index.tsx', null, null],
                name: '(base)_manage_customer-assign',
                path: '/manage/customer-assign',
                handle: {
                  i18nKey: 'route.(base)_manage_customer-assign',
                  title: '(base)_manage_customer-assign',
                  icon: 'mdi:account-arrow-right',
                  order: 1
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/manage/employee-manager/index.tsx', null, null],
                name: '(base)_manage_employee-manager',
                path: '/manage/employee-manager',
                handle: {
                  i18nKey: 'route.(base)_manage_employee-manager',
                  title: '(base)_manage_employee-manager',
                  icon: 'mdi:account-group',
                  order: 3
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/manage/permission/index.tsx', null, null],
                name: '(base)_manage_permission',
                path: '/manage/permission',
                handle: {
                  i18nKey: 'route.(base)_manage_permission',
                  icon: 'carbon:user-admin',
                  order: 1,
                  roles: ['super_admin'],
                  title: '权限管理'
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/manage/role/index.tsx', null, null],
                name: '(base)_manage_role',
                path: '/manage/role',
                handle: {
                  i18nKey: 'route.(base)_manage_role',
                  icon: 'carbon:user-role',
                  order: 2,
                  roles: ['super_admin'],
                  title: 'manage_role'
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/manage/role/[...slug].tsx', null, null],
                    name: '(base)_manage_role_[...slug]',
                    path: '/manage/role/*',
                    handle: {
                      i18nKey: 'route.(base)_manage_role_[...slug]',
                      hideInMenu: true,
                      title: '(base)_manage_role_[...slug]'
                    }
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/manage/user/index.tsx', null, null],
                name: '(base)_manage_user',
                path: '/manage/user',
                handle: {
                  i18nKey: 'route.(base)_manage_user',
                  icon: 'ic:round-manage-accounts',
                  keepAlive: true,
                  order: 1,
                  roles: ['super_admin'],
                  title: 'manage_user'
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/manage/user/[id].tsx', null, null],
                    name: '(base)_manage_user_[id]',
                    path: '/manage/user/:id',
                    handle: {
                      activeMenu: '/manage/user',
                      hideInMenu: true,
                      i18nKey: 'route.(base)_manage_user_[id]',
                      title: '(base)_manage_user_[id]'
                    }
                  }
                ]
              }
            ]
          },
          {
            matchedFiles: [null, null, null, null],
            name: '(base)_meeting-manage',
            path: '/meeting-manage',
            handle: { i18nKey: 'route.(base)_meeting-manage', title: '(base)_meeting-manage' },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/meeting-manage/approve/index.tsx', null, null],
                name: '(base)_meeting-manage_approve',
                path: '/meeting-manage/approve',
                handle: { i18nKey: 'route.(base)_meeting-manage_approve', title: '(base)_meeting-manage_approve' }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/meeting-manage/list/index.tsx', null, null],
                name: '(base)_meeting-manage_list',
                path: '/meeting-manage/list',
                handle: { i18nKey: 'route.(base)_meeting-manage_list', title: '(base)_meeting-manage_list' }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/meeting-manage/record/index.tsx', null, null],
                name: '(base)_meeting-manage_record',
                path: '/meeting-manage/record',
                handle: { i18nKey: 'route.(base)_meeting-manage_record', title: '(base)_meeting-manage_record' }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/meeting-manage/summary/index.tsx', null, null],
                name: '(base)_meeting-manage_summary',
                path: '/meeting-manage/summary',
                handle: { i18nKey: 'route.(base)_meeting-manage_summary', title: '(base)_meeting-manage_summary' }
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(base)/multi-menu/index.tsx', null, null],
            name: '(base)_multi-menu',
            path: '/multi-menu',
            handle: { constant: true, i18nKey: 'route.(base)_multi-menu', order: 5, title: 'multi-menu' },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/multi-menu/first/index.tsx', null, null],
                name: '(base)_multi-menu_first',
                path: '/multi-menu/first',
                handle: { constant: true, i18nKey: 'route.(base)_multi-menu_first', title: 'multi-menu_first' },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/multi-menu/first/child/index.tsx', null, null],
                    name: '(base)_multi-menu_first_child',
                    path: '/multi-menu/first/child',
                    handle: {
                      constant: true,
                      i18nKey: 'route.(base)_multi-menu_first_child',
                      title: 'multi-menu_first_child'
                    }
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/multi-menu/second/index.tsx', null, null],
                name: '(base)_multi-menu_second',
                path: '/multi-menu/second',
                handle: { i18nKey: 'route.(base)_multi-menu_second', title: '(base)_multi-menu_second' },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/multi-menu/second/child/index.tsx', null, null],
                    name: '(base)_multi-menu_second_child',
                    path: '/multi-menu/second/child',
                    handle: {
                      i18nKey: 'route.(base)_multi-menu_second_child',
                      title: '(base)_multi-menu_second_child'
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/multi-menu/second/child/home/index.tsx', null, null],
                        name: '(base)_multi-menu_second_child_home',
                        path: '/multi-menu/second/child/home',
                        handle: {
                          i18nKey: 'route.(base)_multi-menu_second_child_home',
                          title: '(base)_multi-menu_second_child_home'
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            matchedFiles: [null, null, null, null],
            name: '(base)_project-manage',
            path: '/project-manage',
            handle: {
              i18nKey: 'route.(base)_project-manage',
              title: '(base)_project-manage',
              hideInMenu: false,
              icon: 'mdi:clipboard-text-multiple-outline',
              order: 5
            },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/project-manage/list/index.tsx', null, null],
                name: '(base)_project-manage_list',
                path: '/project-manage/list',
                handle: {
                  i18nKey: 'route.(base)_project-manage_list',
                  title: '(base)_project-manage_list',
                  icon: 'mdi:format-list-bulleted',
                  order: 1
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/project-manage/task/index.tsx', null, null],
                name: '(base)_project-manage_task',
                path: '/project-manage/task',
                handle: {
                  i18nKey: 'route.(base)_project-manage_task',
                  title: '(base)_project-manage_task',
                  icon: 'mdi:clipboard-check-outline',
                  order: 2
                }
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(base)/projects/index.tsx', null, null],
            name: '(base)_projects',
            path: '/projects',
            handle: {
              i18nKey: 'route.(base)_projects',
              icon: 'hugeicons:align-box-top-center',
              order: 7,
              title: '(base)_projects'
            },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/projects/[pid]/index.tsx', null, null],
                name: '(base)_projects_[pid]',
                path: '/projects/:pid',
                handle: {
                  i18nKey: 'route.(base)_projects_[pid]',
                  icon: 'material-symbols-light:attachment',
                  title: '(base)_projects_[pid]'
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/projects/[pid]/edit/index.tsx', null, null],
                    name: '(base)_projects_[pid]_edit',
                    path: '/projects/:pid/edit',
                    handle: {
                      i18nKey: 'route.(base)_projects_[pid]_edit',
                      icon: 'material-symbols-light:assistant-on-hub-outline',
                      title: '(base)_projects_[pid]_edit'
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/projects/[pid]/edit/[id].tsx', null, null],
                        name: '(base)_projects_[pid]_edit_[id]',
                        path: '/projects/:pid/edit/:id',
                        handle: {
                          i18nKey: 'route.(base)_projects_[pid]_edit_[id]',
                          title: '(base)_projects_[pid]_edit_[id]'
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(base)/user-center/index.tsx', null, null],
            name: '(base)_user-center',
            path: '/user-center',
            handle: { hideInMenu: true, i18nKey: 'route.(base)_user-center', title: 'user-center' }
          }
        ],
        path: null
      },
      {
        matchedFiles: ['(blank)', null, null, null],
        name: '(blank)',
        children: [
          {
            matchedFiles: ['(blank)_login', '/src/pages/(blank)/login/index.tsx', null, null],
            name: '(blank)_login',
            path: '/login',
            handle: { i18nKey: 'route.(blank)_login', title: '(blank)_login', constant: true },
            children: [
              {
                matchedFiles: [null, '/src/pages/(blank)/login/reset-pwd/index.tsx', null, null],
                name: '(blank)_login_reset-pwd',
                path: '/login/reset-pwd',
                handle: { i18nKey: 'route.(blank)_login_reset-pwd', title: '(blank)_login_reset-pwd', constant: true }
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(blank)/login-out/index.tsx', null, null],
            name: '(blank)_login-out',
            path: '/login-out',
            handle: { i18nKey: 'route.(blank)_login-out', title: '(blank)_login-out', constant: true }
          }
        ],
        path: null
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/403/index.tsx', null, null],
        name: '403',
        path: '/403',
        handle: { i18nKey: 'route.403', title: '403', constant: true }
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/404/index.tsx', null, null],
        name: '404',
        path: '/404',
        handle: { i18nKey: 'route.404', title: '404', constant: true }
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/500/index.tsx', null, null],
        name: '500',
        path: '/500',
        handle: { i18nKey: 'route.500', title: '500', constant: true }
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/iframe-page/index.tsx', null, null],
        name: 'iframe-page',
        path: '/iframe-page',
        handle: { i18nKey: 'route.iframe-page', title: 'iframe-page', constant: true }
      },
      {
        matchedFiles: [null, '/src/pages/notifications/index.tsx', null, null],
        name: 'notifications',
        path: '/notifications',
        handle: { i18nKey: 'route.notifications', title: 'notifications' }
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/404/index.tsx', null, null],
        name: 'notFound',
        path: '*',
        handle: { i18nKey: 'route.notFound', title: 'notFound', constant: true }
      }
    ]
  }
];
